# A curated list of packages
(def packages
  {
   'circlet "https://github.com/janet-lang/circlet.git"
   'pkgs "https://github.com/janet-lang/pkgs.git"
   'path "https://github.com/janet-lang/path.git"
   'json "https://github.com/janet-lang/json.git"
   'sqlite3 "https://github.com/janet-lang/sqlite3.git"
   'argparse "https://github.com/janet-lang/argparse.git"
   'juv "https://github.com/janet-lang/juv.git"
   'mendoza "https://github.com/bakpakin/mendoza.git"
   'tester "https://github.com/joy-framework/tester.git"
   'jurl "https://github.com/sepisoad/jurl.git"
   'joy "https://github.com/joy-framework/joy.git"
   'trolley "https://github.com/pepe/trolley.git"
   'jhydro "https://github.com/janet-lang/jhydro.git"
   'jaylib "https://github.com/janet-lang/jaylib.git"
   'x43bot "https://github.com/bakpakin/x43bot.git"
   'chidi "https://github.com/pepe/chidi.git"
   'spork "https://github.com/janet-lang/spork.git"
   'jurl@bakpakin "https://github.com/bakpakin/jurl.git"
   'process "https://github.com/andrewchambers/janet-process.git"
   'sh "https://github.com/andrewchambers/janet-sh.git"
   'redis "https://github.com/andrewchambers/janet-redis.git"
   'repl-tools "https://github.com/crocket/janet-repl-tools.git"
   'rlrepl "https://github.com/andrewchambers/janet-rlrepl.git"
   'pq "https://github.com/andrewchambers/janet-pq.git"
   'utf8 "https://github.com/crocket/janet-utf8.git"
   'flock "https://github.com/andrewchambers/janet-flock.git"
   'base16 "https://github.com/andrewchambers/janet-base16.git"
   'uri "https://github.com/andrewchambers/janet-uri.git"
   'temple "https://git.sr.ht/~bakpakin/temple"
   'tahani "https://github.com/pepe/tahani.git"
   'jtbox "https://github.com/sepisoad/jtbox.git"
   'miniz "https://github.com/bakpakin/janet-miniz.git"
  })
